[package]
name = "RekordScratch"
version = "0.2.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
indicatif = "0.17"
sysinfo = "0.29"
lofty = "0.17"
walkdir = "2"
anyhow = "1"
dirs = "4.0"
ratatui = "0.25"
crossterm = "0.27"
